kill and reap ProxyCommand
wez/wezterm pull request #5494
Opened 2024-05-31 07:41 UTC by daaku

Using the scopeguard crate ensures the child process (if any) spawned for the ProxyCommand is cleaned up under all the various error scenarios (such as auth failures etc), as well as in the normal successful use case. This ensures killing it if necessary, and then waiting for it.

This is a fix for #5479.

2024-07-13 18:50 UTC, wez requested changes
Thanks for this!
I have a slightly different proposal; would you mind updating to match it?

2024-07-13 18:50 UTC, wez commented on wezterm-ssh/Cargo.toml
> +scopeguard = "1.2.0"
while scopeguard is handy in a pinch, I'm not in favor of it here for a couple of reasons:

* It is an additional external dependency
* You still have to remember to initiate the scope guard, and that is required in multiple places in this PR

What I'd prefer to see as a solution for this is for `connect_to_host` to return a little wrapper around the Child:

```rust
struct KillOnDropChild(Child);

impl std::ops::Deref for KillOnDropChild { ... }
impl std::ops::DerefMut for KillOnDropChild { ... }
impl Drop for KillOnDropChild {
   fn drop(&mut self) {
       self.0.kill();
       self.0.wait();
   }
}
```

2024-07-15 07:24 UTC, daaku commented
Sounds reasonable, I'll update with the requested changes.

2024-07-15 13:14 UTC, merged

2024-07-15 13:14 UTC, wez commented
Thank you!