[terminfo] add smxx/rmxx, purge blink
wez/wezterm pull request #905
Opened 2021-06-27 14:10 UTC by dankamongmen

Testing with WezTerm nightly indicates no blink support
available through the xterm \E[5m, and I didn't see any
support in the code -- purge it. smxx and rmxx, meanwhile,
have been added to indicate support for struck text.

2021-06-27 14:12 UTC, dankamongmen commented
![2021-06-27-101122_1254x1417_scrot](https://user-images.githubusercontent.com/143473/123547776-11aec300-d730-11eb-8abb-9c6e9c22e5ec.png)

huh, i guess i need to edit `termwiz/data/xterm-256color-italic.terminfo` as well, don't i?

2021-06-27 17:08 UTC, wez commented
https://github.com/wez/wezterm/pull/904 is adding blink support!

`termwiz/data/xterm-256color-italic.terminfo` is the `termwiz` crate's fallback for running on a modern xterm compatible system when we either can't find terminfo or are running on windows with virtual terminal support.  It's also used by wezterm's [format](https://wezfurlong.org/wezterm/config/lua/wezterm/format.html) function, but that should really target `wezterm.terminfo` instead.

So: if xterm supports `smxx` and `rmxx` then it makes sense to add it to `xterm-256color-italic.terminfo`, but otherwise not!

2021-06-30 14:36 UTC, wez requested changes

2021-06-30 14:36 UTC, wez commented on termwiz/data/wezterm.terminfo
> +	bel=^G, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
```suggestion
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
```

There's a PR in-flight to make blink, blink, so let's put this bit back!

2021-07-12 04:36 UTC, merged